### ISSUE TITLE
在新的 web 做出来之前怎么办？

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmcore#120]
在 cnpmjs.org 增加一个远程数据的能力，web 还是走原来的方式显示，然后数据源来自新的 registry。

等新版的 web 做好再切换过去。

争取春节期间数据流量比较少，这个时候完成切换。

## TODOs
- [x] cnpmjs.org 页面展示数据来源 r.cnpmjs.org
- [x] npmmirror.com 页面展示来自 registry.npmmirror.com
- [x] 上面完成之后将 cnpmjs.org 页面强制跳转到 npmmirror.com 页面
```ini
  location / {
   #     include /etc/nginx/proxy_params;
   #     proxy_pass http://127.0.0.1:7002;
   #     proxy_redirect off;
       return 302 https://npmmirror.com$request_uri;
   }
```
