### ISSUE TITLE
npm cli commands check list

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmcore#64]
## Done

- [x] [adduser](https://github.com/npm/cli/blob/latest/lib/commands/adduser.js)
- [x] [deprecate](https://github.com/npm/cli/blob/latest/lib/commands/deprecate.js)
- [x] [dist-tag](https://github.com/npm/cli/blob/latest/lib/commands/dist-tag.js) 
- [x] [install](https://github.com/npm/cli/blob/latest/lib/commands/install.js)
- [x] [logout](https://github.com/npm/cli/blob/latest/lib/commands/logout.js)  
- [x] [owner](https://github.com/npm/cli/blob/latest/lib/commands/owner.js) 
- [x] [ping](https://github.com/npm/cli/blob/latest/lib/commands/ping.js)
- [x] [publish](https://github.com/npm/cli/blob/latest/lib/commands/publish.js)
- [x] [repo](https://github.com/npm/cli/blob/latest/lib/commands/repo.js)
- [x] [unpublish](https://github.com/npm/cli/blob/latest/lib/commands/unpublish.js)
- [x] [view](https://github.com/npm/cli/blob/latest/lib/commands/view.js)
- [x] [whoami](https://github.com/npm/cli/blob/latest/lib/commands/whoami.js) 

## Todo

- [ ] [access](https://github.com/npm/cli/blob/latest/lib/commands/access.js)
- [ ] [audit](https://github.com/npm/cli/blob/latest/lib/commands/audit.js)
- [ ] [hook](https://github.com/npm/cli/blob/latest/lib/commands/hook.js)
- [ ] [org](https://github.com/npm/cli/blob/latest/lib/commands/org.js)
- [x] [profile](https://github.com/npm/cli/blob/latest/lib/commands/profile.js) https://github.com/cnpm/cnpmcore/pull/68
```json
GET https://registry.npmjs.org/-/npm/v1/user
npm profile get --json
{
  "tfa": {
    "pending": false,
    "mode": "auth-only"
  },
  "name": "foo",
  "email": "foo@gmail.com",
  "email_verified": true,
  "created": "2015-02-26T01:40:54.959Z",
  "updated": "2021-12-04T17:21:28.461Z",
  "fullname": "foo",
  "twitter": "foo",
  "github": "foo"
}
```

- [ ] [search](https://github.com/npm/cli/blob/latest/lib/commands/search.js)
```bash
GET https://registry.npmjs.org/-/v1/search?text=egg2&size=20&from=0&quality=0.65&popularity=0.98&maintenance=0.5
'npm-command': [ 'search' ],
authorization: [ 'Bearer npm_token' ]

npm search egg --json
[

{"name":"egg","scope":"unscoped","version":"2.33.1","description":"A web framework's framework for Node.js","keywords":["web","app","http","application","framework","middleware","koa","egg"],"date":"2021-12-06T16:26:46.792Z","links":{"npm":"https://www.npmjs.com/package/egg","homepage":"https://github.com/eggjs/egg","repository":"https://github.com/eggjs/egg","bugs":"https://github.com/eggjs/egg/issues"},"publisher":{"username":"fengmk2","email":"fengmk2@gmail.com"},"maintainers":[{"username":"eggjs-admin","email":"fengmk2+eggjs@gmail.com"},{"username":"fengmk2","email":"fengmk2@gmail.com"},{"username":"atian25","email":"atian25@qq.com"},{"username":"dead_horse","email":"dead_horse@qq.com"},{"username":"popomore","email":"sakura9515@gmail.com"},{"username":"wanghx","email":"whxaxes@gmail.com"},{"username":"hyj1991","email":"yeekwanvong@gmail.com"},{"username":"thonatos","email":"thonatos.yang@gmail.com"},{"username":"killagu","email":"killa07071201@gmail.com"},{"username":"coolme200","email":"2001-wms@163.com"},{"username":"xadillax","email":"admin@xcoder.in"},{"username":"ngot","email":"zhuanghengfei@gmail.com"},{"username":"mansonchor.zzw","email":"mansonchor1987@gmail.com"},{"username":"hubcarl","email":"hubcarl@126.com"},{"username":"shaoshuai0102","email":"shaoshuai0102@gmail.com"}]}

,

{"name":"egg-mock","scope":"unscoped","version":"4.2.0","description":"mock server for egg","keywords":["egg","mock"],"date":"2021-12-17T10:44:58.662Z","links":{"npm":"https://www.npmjs.com/package/egg-mock","homepage":"https://github.com/eggjs/egg-mock","repository":"https://github.com/eggjs/egg-mock","bugs":"https://github.com/eggjs/egg/issues"},"author":{"name":"popomore","email":"sakura9515@gmail.com","username":"popomore"},"publisher":{"username":"fengmk2","email":"fengmk2@gmail.com"},"maintainers":[{"username":"eggjs-admin","email":"fengmk2+eggjs@gmail.com"},{"username":"fengmk2","email":"fengmk2@gmail.com"},{"username":"atian25","email":"atian25@qq.com"},{"username":"dead_horse","email":"dead_horse@qq.com"},{"username":"popomore","email":"sakura9515@gmail.com"},{"username":"wanghx","email":"whxaxes@gmail.com"},{"username":"hyj1991","email":"yeekwanvong@gmail.com"},{"username":"thonatos","email":"thonatos.yang@gmail.com"},{"username":"killagu","email":"killa07071201@gmail.com"},{"username":"coolme200","email":"2001-wms@163.com"},{"username":"xadillax","email":"admin@xcoder.in"},{"username":"ngot","email":"zhuanghengfei@gmail.com"},{"username":"mansonchor.zzw","email":"mansonchor1987@gmail.com"},{"username":"hubcarl","email":"hubcarl@126.com"},{"username":"shaoshuai0102","email":"shaoshuai0102@gmail.com"}]}
```

- [x] [star](https://github.com/npm/cli/blob/latest/lib/commands/star.js) https://github.com/cnpm/cnpmcore/pull/65
- [x] [unstar](https://github.com/npm/cli/blob/latest/lib/commands/unstar.js) https://github.com/cnpm/cnpmcore/pull/65
- [x] [stars](https://github.com/npm/cli/blob/latest/lib/commands/stars.js) https://github.com/cnpm/cnpmcore/pull/65
```bash
GET http://localhost:7001/-/_view/starredByUser?key=%22cnpmcore_admin%22
```

- [ ] [team](https://github.com/npm/cli/blob/latest/lib/commands/team.js)
- [ ] [token](https://github.com/npm/cli/blob/latest/lib/commands/token.js)
- [ ] [version](https://github.com/npm/cli/blob/latest/lib/commands/version.js)
